### PR TITLE
feat(item): Item update

### PR DESCRIPTION
**Pull request by dark0dave**
Update setup.tra, very small fixes. Items look a bit nicer in game (ee)

### CODE REVIEW

**Comment by Gitjas** [comment]
Please have a look at the setup_ee.tra. The setup.tra is for oldBG2 so the syntax should match that.

**Comment by Gitjas** [comment]
Hmm, seems the problem is that the setup_ee.tra doesn't get loaded for ee?

**Comment by dark0dave** [comment]
> Hmm, seems the problem is that the setup_ee.tra doesn't get loaded for ee?

Yes @Gitjas exactly. Look at the tp2 file. Its commented out the setup_ee.tra is also missing loads of strings.

**Comment by Gitjas** [comment]
Yes. Still, setup.tra is for oldBG2. The change needed is to load setup_ee.tra for an EE install.
Note that setup_ee.tra is loaded in addition to the setup.tra, so not all strings need to go in there, only the ones that would differ (i.e. item descriptions).
I don't know when I'll find time for these changes. I'll close this for now. Thank you for the heads up.

**Comment by Gitjas** [comment]
EE item descriptions get loaded now with version Beta 8.
Thanks again for drawing my attention to this.

**Pull request closed without merging**
